Update Show page
Improwised/phoenix-frontend-shailja-goswami pull request #10
Opened 2023-05-02 11:05 UTC by shailja-imw

=> fetch api to fill the from 
=> updated API call

2023-05-02 13:11 UTC, monikagorkhiya requested changes

2023-05-02 13:11 UTC, monikagorkhiya commented on app/pages/[id]/update.vue
> +  title: '',
Is it compulsory to define as blank?

2023-05-02 13:24 UTC, shailja-imw commented on app/pages/[id]/update.vue
> +  title: '',
For the schema purpose, I have added. we can even remove it also. but for update I think we need it

2023-05-04 07:17 UTC, monikagorkhiya approved these changes

2023-05-04 07:17 UTC, merged