delete the show
Improwised/phoenix-frontend-shailja-goswami pull request #13
Opened 2023-05-03 10:54 UTC by shailja-imw

=>Show delete API call

2023-05-04 07:22 UTC, monikagorkhiya requested changes

2023-05-04 07:22 UTC, monikagorkhiya commented on app/components/Shows.vue
> +  if (confirm('Are you sure you wanted to remove ' + show + ' this show')) {
You can put bootstrap modal

2023-05-04 07:23 UTC, monikagorkhiya requested changes

2023-05-04 07:23 UTC, monikagorkhiya commented on app/components/Shows.vue
> +                  @click="deleteShow(show.id, show.title)"
Where this is used?

2023-05-04 07:38 UTC, shailja-imw commented on app/components/Shows.vue
> +  if (confirm('Are you sure you wanted to remove ' + show + ' this show')) {
okay

2023-05-04 07:39 UTC, shailja-imw commented on app/components/Shows.vue
> +                  @click="deleteShow(show.id, show.title)"
I had used the bootstrap modal but then I did with the alert confirm

2023-05-05 06:08 UTC, monikagorkhiya approved these changes

2023-05-05 06:08 UTC, merged