PR for Header : header design added
Improwised/phoenix-frontend-shailja-goswami pull request #4
Opened 2023-04-27 10:37 UTC by shailja-imw

=>Header design added

2023-04-27 13:15 UTC, shailja-imw commented
**Layout Header and Footer**

![image](https://user-images.githubusercontent.com/129731184/234872911-a490e157-169b-4726-a624-31039ac56c15.png)

2023-04-27 13:51 UTC, monikagorkhiya requested changes

2023-04-27 13:51 UTC, monikagorkhiya commented on app/app.vue
> +      <div class="container">
App.vue you can remove also , in the layout you can directly get the pages. 
but This way is also proper
i think container should be use section wise

2023-04-27 13:51 UTC, monikagorkhiya commented on app/layouts/default.vue
> +      <slot></slot>
here you can use NuxtPage

2023-04-28 04:56 UTC, shailja-imw commented on app/app.vue
> +      <div class="container">
Ok, So I will remove the app.vue and in index, I will use <NuxtPage> .

2023-04-28 06:09 UTC, Payal17122000 requested changes

2023-04-28 06:09 UTC, Payal17122000 commented on app/assets/css/main.css
> +body {
not use direct style for tag

2023-04-28 06:09 UTC, Payal17122000 commented on app/assets/css/main.css
> +a {
again not use direct style to tag

2023-04-28 06:29 UTC, Payal17122000 approved these changes

2023-04-28 06:34 UTC, monikagorkhiya requested changes

2023-04-28 06:34 UTC, monikagorkhiya commented on app/layouts/default.vue
> +                  >Add Show</NuxtLink
Please add this as a btn in Discover page

2023-04-28 06:39 UTC, shailja-imw commented on app/layouts/default.vue
> +                  >Add Show</NuxtLink
Add show need to replace from here to discover page?

2023-04-28 07:08 UTC, monikagorkhiya approved these changes

2023-04-28 07:09 UTC, merged