Discover page
Improwised/phoenix-frontend-shailja-goswami pull request #7
Opened 2023-04-28 08:41 UTC by shailja-imw

=> card design

2023-04-28 11:22 UTC, shailja-imw commented
Design
![Nuxt3](https://user-images.githubusercontent.com/129731184/235134833-f8f82dfd-38ab-436f-b4aa-ce0c26da8d44.png)

2023-04-28 11:58 UTC, shailja-imw commented
![image](https://user-images.githubusercontent.com/129731184/235141564-7a1a80d1-286a-40bf-8b9b-06cbbf6966bb.png)

2023-05-01 07:21 UTC, monikagorkhiya requested changes

2023-05-01 07:21 UTC, monikagorkhiya commented on app/assets/css/main.css
> +  margin-bottom: 244px;
?? why need this huge number pixel to margin ?

2023-05-01 07:21 UTC, monikagorkhiya commented on app/pages/index.vue
> -  margin-top: 400px;
Same here why need a custom margin?

2023-05-01 07:21 UTC, monikagorkhiya commented on app/pages/discover/index.vue
> +const { data: showsData, pending } = await useLazyAsyncData('showsData', () =>
Is that Possible via useAsyncData instead of Lazy?

2023-05-01 07:21 UTC, monikagorkhiya commented
Please share Snapshot in the PR

2023-05-01 08:01 UTC, shailja-imw commented on app/assets/css/main.css
> +  margin-bottom: 244px;
As I am using the header in the fixed position that why I have used the margin.

2023-05-01 08:17 UTC, shailja-imw commented on app/pages/discover/index.vue
> +const { data: showsData, pending } = await useLazyAsyncData('showsData', () =>
Yes, we can use it. As I was using get API that's why I was using It, as per our discussion I will update it to make it consistent

2023-05-01 11:17 UTC, monikagorkhiya approved these changes

2023-05-01 11:17 UTC, merged