Add shows
Improwised/phoenix-frontend-shailja-goswami pull request #8
Opened 2023-05-01 11:02 UTC by shailja-imw

=>Form design
=> API call
=> on success  message

2023-05-01 11:04 UTC, shailja-imw commented
![image](https://user-images.githubusercontent.com/129731184/235443755-f27ba146-0141-44e4-afe6-97a6a512bd7f.png)

2023-05-01 12:09 UTC, monikagorkhiya requested changes

2023-05-01 12:09 UTC, monikagorkhiya commented on app/pages/add.vue
> +      ref="addUpdateForm"
why need ref?

2023-05-01 12:09 UTC, monikagorkhiya commented on app/components/FormShows.vue
> +  type: type.value,
Can we reduce the code here?

2023-05-01 12:09 UTC, monikagorkhiya commented on app/components/FormShows.vue
> +  details = {
Can we reduce the code here?

2023-05-01 12:09 UTC, monikagorkhiya commented on app/components/FormShows.vue
> +  console.log(details)
remove console.log

2023-05-02 04:54 UTC, shailja-imw commented on app/pages/add.vue
> +      ref="addUpdateForm"
no need of the ref I was trying something else and forgot to remove the ref. I will remove it.

2023-05-02 04:55 UTC, shailja-imw commented on app/components/FormShows.vue
> +  type: type.value,
yes I am trying for the alternative ways to reduce the code and optimise it

2023-05-02 04:55 UTC, shailja-imw commented on app/components/FormShows.vue
> +  console.log(details)
ok

2023-05-02 10:36 UTC, merged